

name: Github Actions Demo - Prod
on:
  push:
    branches:
      - prod
      - develop
      - develop-0

jobs: 
  Development-Github-Action:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered For the dev branch by a ${{ github.event_name }} event."
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

  Development-0-Github-Action:
    runs-on: ubuntu-latest
    environment: develop
    steps:
        - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Build Docker Image
          run: docker build -t react-docker:1.0.0-prod  

  Prod-Github-Action:
    runs-on: ubuntu-latest
    environment: prod
    steps:
        - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v2
        - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}
        - run: echo "ğŸ The job's status is ${{ job.status }}." 